---

plugins:
  - jest
  - babel
  - react

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

settings:
  react:
    version: 'latest'

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    legacyDecorators: true

env:
  browser: true
  node: true
  jest: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  react/jsx-filename-extension: 0
  global-require: 0
  no-underscore-dangle: 0
